version: "3"

services:
  front:
    image: frontend1
    depends_on:
      - app
    ports:
      - "80:3000"
  app:
    image: server1
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mongo
