version: "3"

services:
  front:
    image: frontend
    depends_on:
      -server
    ports:
      - "80:8080"
  app:
    image: server
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mongo
